
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant"
  config.ssh.insert_key = false
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "v'"
  end
  config.vm.provider "docker" do |d|
    d.image = "centos:latest"
    d.remains_running = true
    d.has_ssh = false
  end
end
